Fix CI (#1805)
* exit tests

* tries logging error

* tries need all stages

* moves failure check to top

* tries checking status

* tries failure env variable

* tries checking verify

* tries if

* fail if build fails

* should be mergable when successful

diff --git a/.github/workflows/on-push-branch.yml b/.github/workflows/on-push-branch.yml
--- a/.github/workflows/on-push-branch.yml
+++ b/.github/workflows/on-push-branch.yml
@@ -70,16 +70,43 @@ jobs:
     environment:
       name: Branch
       url: ${{ steps.setup.outputs.crn-app-url }}
-    needs: [verify]
-    if: success()
+    needs: [test, build, build-analysis, create-environment, deployment, verify]
+    if: ${{ always() }}
     steps:
       - name: Checkout
+        if: ${{ success() }}
         uses: actions/checkout@v3
       - name: Setup
         id: setup
         uses: ./.github/actions/setup-environment
         with:
           environment-name: Branch
-      - name: Print success
+      - name: Print status
         run: |
-          echo "Pipeline branch successful."
+          function statusIcon () {
+            if [ "$1" == "success" ]; then
+              echo ":tada:"
+            else
+              echo ":warning:"
+            fi
+          }
+          echo "# Pipeline branch CI/CD" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "## Summary" >> $GITHUB_STEP_SUMMARY
+          echo "| stage | status |" >> $GITHUB_STEP_SUMMARY
+          echo "| ----- | ------ |" >> $GITHUB_STEP_SUMMARY
+          echo "| test | $(statusIcon ${{  needs.test.result }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| build |  $(statusIcon ${{ needs.build.result }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| build-analysis | $(statusIcon ${{ needs.build-analysis.result }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| create-environment | $(statusIcon ${{ needs.create-environment.result }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| deployment | $(statusIcon ${{ needs.deployment.result }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| verify | $(statusIcon ${{ needs.verify.result }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+      - name: On failure
+        if: ${{ !contains(needs.verify.result, 'success')}}
+        run: |
+          echo "Build Failed! :fire:" >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: On success
+        run: |
+          echo "Build Success! :rocket:" >> $GITHUB_STEP_SUMMARY
