Add limit check.

diff --git a/.github/workflows/reusable-create-environment.yml b/.github/workflows/reusable-create-environment.yml
--- a/.github/workflows/reusable-create-environment.yml
+++ b/.github/workflows/reusable-create-environment.yml
@@ -57,9 +57,16 @@ jobs:
           contentful-master-env: ${{ steps.setup.outputs.contentful-environment }}
           contentful-token: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
           max-contentful-envs: ${{ steps.setup.outputs.max-contentful-envs }}
+      - name: Ensure that we are not at Contentful environment limit
+        id: ensure-limit-not-reached
+        if: ${{ steps.get-contentful-state.outputs.on-branch-env == 'True' && steps.get-contentful-state.outputs.contentful-env-exists == 'False' && steps.get-contentful-state.outputs.contentful-limit-reached == 'True' }}
+        shell: bash
+        run: |
+          echo "Contentful Environment required but all available slots are in use."
+          exit 1
       - name: Create Contentful environment
         id: create-contentful-environment
-        if: ${{ steps.get-contentful-state.outputs.on-branch-env == 'True' && steps.get-contentful-state.outputs.contentful-env-exists == 'False' }}
+        if: ${{ steps.get-contentful-state.outputs.on-branch-env == 'True' && steps.get-contentful-state.outputs.contentful-env-exists == 'False' && steps.get-contentful-state.outputs.contentful-limit-reached == 'False' }}
         shell: bash
         run: bash .github/scripts/contentful/create.sh
         env:
